### PR TITLE
Add s-urbaniak, remove marun from OWNERS

### PR DESCRIPTION
**Pull request by marun**
/cc @stlaz @sttts

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

it's not obvious to me how @marun lost his knowledge of this repo and needs to be removed or how @s-urbaniak gained enough knowledge to become an approver.

**Comment by marun** [comment]
> /hold
> 
> it's not obvious to me how @marun lost his knowledge of this repo and needs to be removed or how @s-urbaniak gained enough knowledge to become an approver.

The intention was to transition me to the role of an unofficial advisor. It's challenging to fulfull my responsibilities to the etcd team if I remain on the hook for everything I've done before.

It wouldn't prevent reviewing as needed, and I would trust @s-urbaniak not to merge PRs that he doesn't understand without input from those that do.

**Comment by sttts** [comment]
This component used to be owned by my team, and now transitions to @s-urbaniak. @marun is on-board with this change.

/lgtm
/approve

**Pull request merged**
