### PR TITLE
Remove unnecessary permissions for controllers

### PR DESCRIPTION
**Pull request by marun**
The [controller unification PR](https://github.com/openshift/service-ca-operator/pull/89) added permissions for removing 4.3 resources to the role used by controllers but removal will be performed by the operator which has cluster admin privileges.

/cc @stlaz

### CODE REVIEW

**Comment by marun** [comment]
Rebased

**Comment by stlaz** [comment]
/lgtm
I should have noticed that when I pointed out the perms weren't enough to remove the deployment

**Pull request merged**
