### PR TITLE
Configure explicit user and group for pod's SecurityContext

### LINKED ISSUE #237: Operator image runs as root (which does not work for Kubernetes distributions other than OpenShift)
https://github.com/openshift/service-ca-operator/blob/f409fb9e308ace1e5f8596add187d2239b073e23/bindata/v4.0.0/controller/deployment.yaml#L33-L34

https://github.com/openshift/service-ca-operator/blob/f409fb9e308ace1e5f8596add187d2239b073e23/pkg/operator/v4_00_assets/bindata.go#L214-L215

When I try to run the operator in a non-openshift Kubernetes (I tried KinD and K3D), I get this error from the pod created from the deployment created in the snippet above

```
Warning  Failed     9m39s (x12 over 11m)  kubelet            Error: container has runAsNonRoot and image will run as root
(pod: "service-ca-74959bd5c-rf7qz_openshift-service-ca(b04cb30f-09c0-4cf8-a5a0-ccc4d296ba70)", container: service-ca-controller) 
```

The image in question is

```
quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b38c14341015df2db595538f4933ed94fd9f6c283dfc9c5dae7540d9d9ae59ed
```

Looking at https://github.com/openshift/service-ca-operator/blob/master/Dockerfile.rhel7, it does not switch `USER` anywhere.

This is fine on OpenShift, because

> By default, OpenShift Container Platform runs containers using an arbitrarily assigned user ID.
>
> https://docs.openshift.com/container-platform/4.6/openshift_images/create-images.html

But it is not OK elsewhere, where it is causing the error I am facing.

NB. I saw similar issue in skupper-router, https://github.com/skupperproject/skupper/pull/937#pullrequestreview-1165464425

### PR DESCRIPTION
**Pull request by jiridanek**
* Fixes #237

I haven't figured out how to build this so I can test it by hand and run e2e tests.

```
podman build . -f Dockerfile.rhel7
[1/2] STEP 1/5: FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15 AS builder
Trying to pull registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15...
Error: creating build container: initializing source docker://registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15: reading manifest rhel-8-golang-1.20-openshift-4.15 in registry.ci.openshift.org/ocp/builder: authentication required
```

### CODE REVIEW

**Comment by jiridanek** [comment]
There is this other somewhat related PR around

* https://github.com/openshift/service-ca-operator/issues/

just FYI

**Comment by stlaz** [comment]
/close
This PR would make the controller fail to start after the changes done in https://github.com/openshift/service-ca-operator/pull/235.
The above PR should actually also fix the original issue.

**Comment by jiridanek** [comment]
@stlaz thanks, can you still help me with my question about how to build the project's Dockerfile with podman?

```
podman build . -f Dockerfile.rhel7
[1/2] STEP 1/5: FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15 AS builder
Trying to pull registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15...
Error: creating build container: initializing source docker://registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15: reading manifest rhel-8-golang-1.20-openshift-4.15 in registry.ci.openshift.org/ocp/builder: authentication required
```

🤷🏽 

Later today I'll go try whatever is the current image from main that should be in quay.io somewhere after openshift-ci built it.

**Comment by stlaz** [comment]
Sure.

There are two options as far as I can tell. One of the options is that you're able to use your Red Hat credentials to log in to the CI cluster at https://api.ci.l2s4.p1.openshiftapps.com:6443/ and you then use the token for that cluster to pull the build and runtime images from the registry.

An alternative would be to replace the RHEL-based images with different, publicly accessible images. I believe OKD must be building our images differently, https://github.com/okd-project/okd might be worth checking.

**Comment by jiridanek** [comment]
This somewhat! I found https://github.com/okd-project/okd/discussions/1824, that suggested I should do

```
skopeo inspect docker://quay.io/openshift/okd-content@sha256:e4ad66ee0157671c8a613790bd36e9ddc26b26fbc8f65114b4982a4d6b04ee5b
```

and that was not helpful at all, so I did

```
jdanek@fedora:~$ podman pull quay.io/openshift/okd-content@sha256:e4ad66ee0157671c8a613790bd36e9ddc26b26fbc8f65114b4982a4d6b04ee5b
Trying to pull quay.io/openshift/okd-content@sha256:e4ad66ee0157671c8a613790bd36e9ddc26b26fbc8f65114b4982a4d6b04ee5b...
podman hisGetting image source signatures
Copying blob 97da74cc6d8f skipped: already exists  
Copying blob 255506d970e9 done   | 
Copying blob ed852e4914a0 done   | 
Copying blob 61ca390a4fc5 done   | 
Copying blob d15b7f1fe13e done   | 
Copying blob d8190195889e skipped: already exists  
Copying config a8f9f4bdae done   | 
Writing manifest to image destination
a8f9f4bdae55b759f53b929c3eeed03f7f7e198d2ff6a650918f5dc24ab10bf2
jdanek@fedora:~$ podman history quay.io/openshift/okd-content@sha256:e4ad66ee0157671c8a613790bd36e9ddc26b26fbc8f65114b4982a4d6b04ee5b
ID            CREATED        CREATED BY                                     SIZE        COMMENT
a8f9f4bdae55  4 months ago   /bin/sh -c #(nop) LABEL "io.openshift.buil...  96.4MB      FROM image-registry.openshift-image-registry.svc:5000/ci-op-9ii37qvq/pipeline@sha256:fe827bd220dc2ff1e0816f35d648091906a2f22960d73e97036297d5cf62fed2
<missing>     4 months ago   /bin/sh -c #(nop) ENV "OPENSHIFT_BUILD_NAM...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) LABEL io.openshift.relea...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ENTRYPOINT ["/usr/bin/se...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) COPY file:274a48ced173d7...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) COPY dir:439735eb4047adb...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) COPY file:51f8b75aa43885...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ENV "BUILD_LOGLEVEL"="0"     0B          
<missing>     4 months ago   /bin/sh -c #(nop) LABEL "io.openshift.buil...  2.32MB      FROM image-registry.openshift-image-registry.svc:5000/ocp/builder@sha256:a05267d20241b182e8211ee03bdb75774c42afd021d4617c4bb85ff3956936e2
<missing>     4 months ago   /bin/sh -c #(nop) ENV "OPENSHIFT_BUILD_NAM...  0B          
<missing>     4 months ago   /bin/sh -c echo -e '[localdev-rhel-8-serve...  0B          
<missing>     4 months ago   /bin/sh -c echo -e '[localdev-rhel-8-serve...  0B          
<missing>     4 months ago   /bin/sh -c echo -e '[localdev-rhel-8-fast-...  0B          
<missing>     4 months ago   /bin/sh -c echo -e '[localdev-rhel-8-coder...  0B          
<missing>     4 months ago   /bin/sh -c echo -e '[localdev-rhel-8-baseo...  0B          
<missing>     4 months ago   /bin/sh -c echo -e '[localdev-rhel-8-appst...  0B          
<missing>     4 months ago   /bin/sh -c echo -e '[localdev-openstack-16...  0B          
<missing>     4 months ago   /bin/sh -c yum config-manager --setopt=ski...  0B          
<missing>     4 months ago   /bin/sh -c rm -rf /etc/yum.repos.d/*.repo ...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) USER 0                       0B          
<missing>     4 months ago   /bin/sh -c #(nop) LABEL io.k8s.description...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) LABEL io.k8s.display-nam...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ENV OPENSHIFT_CI=true        0B          
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  36.9MB      FROM registry-proxy.engineering.redhat.com/rh-osbs/openshift-base-rhel8@sha256:128b1488c16a66ea416494bfe6b73f43246c84c2fe0a65820c3cf7995eb27d1b
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  0B          
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) LABEL "com.redhat.licens...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ADD file:5ce4097bbe35243...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ADD file:951b27a236dcc96...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) LABEL         io.k8s.dis...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ENV GODEBUG=x509ignoreCN...  0B          
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ENV __doozer=merge OS_GI...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ENV __doozer=update BUIL...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ADD file:60d3fd031083dfa...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ADD file:ecc29a1455ca1b7...  0B          
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ARG REMOTE_SOURCES REMOT...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ARG REMOTE_SOURCES           0B          
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  178MB       FROM registry-proxy.engineering.redhat.com/rh-osbs/rhel-els@sha256:ae88d68c3ba828bfac144a6561f9300af68fc5d6f332785e10e845cc2a48b2a3
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  0B          
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) LABEL "com.redhat.licens...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ADD file:b2e0dc699e8400c...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ADD file:499199319045f4e...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) LABEL         name="open...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) COPY file:625cb223e009f1...  0B          
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ENV __doozer=merge OS_GI...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ENV __doozer=update BUIL...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ADD file:6ea2f2a61c20c36...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ADD file:ecc29a1455ca1b7...  0B          
<missing>     4 months ago   |2 REMOTE_SOURCES=unpacked_remote_sources ...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ARG REMOTE_SOURCES REMOT...  0B          
<missing>     4 months ago   /bin/sh -c #(nop) ARG REMOTE_SOURCES           0B          
<missing>     18 months ago                                                 20.5kB      
<missing>     18 months ago                                                 227MB       Imported from -
```

which reveals that ocp/builder is also used for okd

**Pull request closed without merging**
