### PR TITLE
bug 1700903: standardize names for api freeze

### PR DESCRIPTION
**Pull request by ericavonb**
Remove "openshift-" prefix from the resource names for auth components

### CODE REVIEW

**Comment by ericavonb** [comment]
/retest 
I don't know that this is a flake but also not sure what's wrong 😞

**Comment by mrogers950** [comment]
The last flake is different and looks like a total blowup instead
/retest

**Comment by sjenning** [comment]
FYI, this broke my upgrade
```
$ oc logs service-ca-operator-7d49f8d787-wqbxx | grep E0 | tail -n4
E0424 02:47:46.628093       1 controller.go:117] {ServiceCAOperator ServiceCAOperator} failed with: Deployment.apps "service-serving-cert-signer" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"service-serving-cert-signer", "service-serving-cert-signer":"true"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
E0424 02:48:12.847326       1 controller.go:117] {ServiceCAOperator ServiceCAOperator} failed with: Deployment.apps "service-serving-cert-signer" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"service-serving-cert-signer", "service-serving-cert-signer":"true"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
E0424 02:48:15.260855       1 controller.go:117] {ServiceCAOperator ServiceCAOperator} failed with: Deployment.apps "service-serving-cert-signer" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"service-serving-cert-signer", "service-serving-cert-signer":"true"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
E0424 02:53:41.875156       1 controller.go:117] {ServiceCAOperator ServiceCAOperator} failed with: Deployment.apps "service-serving-cert-signer" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"service-serving-cert-signer", "service-serving-cert-signer":"true"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
```
$ oc get deployment -n openshift-service-ca service-serving-cert-signer -ojson | jq .spec.selector
{
  "matchLabels": {
    "app": "openshift-service-serving-cert-signer",
    "service-serving-cert-signer": "true"
  }
}
```
Just something to keep in mind when, one day, we don't break upgrades any more.  One day...

**Pull request merged**
