### PR TITLE
Bug 1703229: Increase leader election values

### PR DESCRIPTION
**Pull request by mrogers950**
These values are not as aggressive and are still reasonable for the CA rotation process' deployment time. 
@openshift/sig-auth 

https://bugzilla.redhat.com/show_bug.cgi?id=1703229

### CODE REVIEW

**Comment by enj** [comment]
/hold

Matt will do a bump and remove our explicit setting of these values since they are based on https://github.com/openshift/library-go/pull/361

This is all predicated on the audit logs telling us what is actually causing the writes.

**Comment by mrogers950** [comment]
@enj updated with bump

**Comment by eparis** [comment]
the "authentication" clusteroperator failed with:
`"message": "Progressing: got '404 Not Found' status while trying to GET the OAuth well-known https://10.0.132.43:6443/.well-known/oauth-authorization-server endpoint data",`

**Comment by eparis** [comment]
what that caused by this PR?

**Comment by mrogers950** [comment]
> what that caused by this PR?

I don't think so, looking at the logs there were no cert changes at that time

/retest

**Pull request merged**
