### PR TITLE
[4.5] Bug 1880360: Fix bug in reflector not recovering from "Too large resource version"

### PR DESCRIPTION
**Pull request by vareti**
This bumps imports the recent fix in reflector/informer that was made in upstream client-go

https://github.com/kubernetes/kubernetes/pull/92688

### CODE REVIEW

**Comment by marun** [comment]
@vareti For future, it's fine to combine the manual go.mod changes and the go mod bump in a single commit.

/lgtm
/bugzilla refresh

**Comment by vareti** [comment]
@marun Sure. I always get confused whether to use single commit or split manual changes to separate commit. But I will try to keep this mind from now on.

**Comment by stlaz** [comment]
/retitle [4.5] Bug 1880360: Fix bug in reflector not recovering from "Too large resource version"

**Pull request merged**
